name: SonarCloud scan
on:
  workflow_dispatch:
  workflow_call:
    secrets:
        SONAR_TOKEN:
          description: 'Token for SonarCloud'
          required: true 
jobs:
  sonarcloud:
    name: Run SonarCloud scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}